config/routes.rb
Rails.application.routes.draw do

  root 'posts#index'
  
  resources :posts

end

app/models/post.rb
class Post < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def index
    @posts = Post.all
  end

  def new
    @post = Post.new
  end

  def edit
    
  end

  def create
    @post = Post.new(post_params)
    if @post.save
      flash[:notice] = "Post stworzony"
      redirect_to posts_path
    else
      flash[:alert] = "Coś zjebałeś"
      render :new
    end
  end

  private

  def post_params
    params.require(:post).permit(:content, :title)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Costam</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/posts/index.html.erb
<%= link_to 'Nowy post', new_post_path %>
<table style="width:100%">
  <tr>
    <th>Title</th>
    <th>Content</th> 
  </tr>
  <%- @posts.each do |post| %>
    <tr>
      <td><%=post.title%></td>
      <td><%=post.content%></td> 
    </tr>
  <% end %>

app/views/posts/new.html.erb
<%= form_for @post do |f| %>
  <%= f.text_field :title %>
  <%= f.text_area :content %>
  <%= f.submit %>
<% end %>